# Generated by Django 5.2.7 on 2025-10-27 00:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_uid', models.CharField(help_text='Уникальный идентификатор устройства', max_length=100, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_latlon', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('sim_number', models.CharField(blank=True, max_length=20, null=True)),
                ('last_seen_via', models.CharField(blank=True, choices=[('BLE', 'Bluetooth Low Energy'), ('HTTP', 'HTTP'), ('LTE', 'LTE')], max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationTrack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latlon', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('direction', models.FloatField(blank=True, help_text='Направление в градусах', null=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', '-created_at'], name='devices_loc_device__50ead3_idx')],
            },
        ),
    ]
