# Generated by Django 5.2.7 on 2025-10-27 01:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('latlon', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('detected_type', models.CharField(choices=[('FALL_DETECTED', 'Fall Detected'), ('MANUAL_TRIGGER', 'Manual Trigger'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('severity', models.PositiveSmallIntegerField(default=1)),
                ('timestamp', models.DateTimeField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('dedup_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_events', to='devices.device')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_sos', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='sos_soseven_timesta_d650bd_idx')],
            },
        ),
    ]
