# Generated by Django 5.2.7 on 2025-12-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIncidentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_incidents', models.PositiveIntegerField(default=0)),
                ('resolved_count', models.PositiveIntegerField(default=0)),
                ('false_alarms', models.PositiveIntegerField(default=0)),
                ('avg_response_time_seconds', models.FloatField(default=0.0)),
                ('type_distribution', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Statistic',
                'verbose_name_plural': 'Daily Statistics',
                'ordering': ['-date'],
            },
        ),
    ]
